{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "version": "1.0.0",
  "lastUpdated": "2026-02-16",
  "description": "Matriz de permissões por perfil - fonte única de RBAC",
  "roles": {
    "programador": {
      "nivel": 1,
      "label": "Programador",
      "descricao": "Dono do sistema - acesso total incluindo TI/Ops",
      "permissoes": [
        "DASH_VIEW_OPER",
        "DASH_VIEW_EXEC",
        "CAL_VIEW",
        "CAL_CREATE_EVENT",
        "CAL_EDIT_EVENT",
        "CAL_DELETE_EVENT",
        "OBRA_VIEW",
        "OBRA_CREATE",
        "OBRA_EDIT",
        "OBRA_DELETE",
        "SUP_VIEW",
        "SUP_REQUEST",
        "SUP_APPROVE",
        "SUP_OC_CREATE",
        "SUP_OC_APPROVE",
        "SUP_OC_DELETE",
        "EST_VIEW",
        "EST_RECEIVE",
        "EST_TRANSFER",
        "EST_ADJUST",
        "LOG_VIEW",
        "LOG_CREATE_TRIP",
        "LOG_APPROVE_TRIP",
        "EQUIP_VIEW",
        "EQUIP_SCHEDULE",
        "EQUIP_MAINTAIN",
        "FIN_VIEW",
        "FIN_LANC_CREATE",
        "FIN_AP_CREATE",
        "FIN_AP_PAY",
        "FIN_AR_CREATE",
        "FIN_AR_RECEIVE",
        "FIN_CONCIL",
        "CAD_VIEW",
        "CAD_EDIT",
        "RH_VIEW",
        "RH_APONTAR",
        "RH_VER_SALARIO",
        "RH_EDIT_SALARIO",
        "REPORT_VIEW",
        "BI_VIEW",
        "ADMIN_USERS",
        "ADMIN_PERFIS",
        "TI_OPS",
        "TI_OPS_ROLLBACK",
        "TI_OPS_SNAPSHOT",
        "TI_OPS_CERTIFICACAO",
        "TI_AUDITORIA",
        "SETTINGS_SYSTEM",
        "SETTINGS_GLOBAL"
      ],
      "menus": [
        "dashboard",
        "calendario",
        "obras",
        "suprimentos",
        "estoques",
        "logistica",
        "equipamentos",
        "financeiro",
        "cadastros",
        "rh",
        "relatorios",
        "administracao",
        "ativos",
        "implementacoes",
        "ti",
        "ajuda",
        "assistentes-ia",
        "atalhos",
        "notificacoes",
        "ajustes"
      ]
    },
    "geral": {
      "nivel": 2,
      "label": "Geral (Admin Empresa)",
      "descricao": "Admin da empresa contratante - quase tudo, sem TI/Ops do produto",
      "permissoes": [
        "DASH_VIEW_OPER",
        "DASH_VIEW_EXEC",
        "CAL_VIEW",
        "CAL_CREATE_EVENT",
        "CAL_EDIT_EVENT",
        "CAL_DELETE_EVENT",
        "OBRA_VIEW",
        "OBRA_CREATE",
        "OBRA_EDIT",
        "SUP_VIEW",
        "SUP_REQUEST",
        "SUP_APPROVE",
        "SUP_OC_CREATE",
        "SUP_OC_APPROVE",
        "EST_VIEW",
        "EST_RECEIVE",
        "EST_TRANSFER",
        "EST_ADJUST",
        "LOG_VIEW",
        "LOG_CREATE_TRIP",
        "LOG_APPROVE_TRIP",
        "EQUIP_VIEW",
        "EQUIP_SCHEDULE",
        "EQUIP_MAINTAIN",
        "FIN_VIEW",
        "FIN_LANC_CREATE",
        "FIN_AP_CREATE",
        "FIN_AP_PAY",
        "FIN_AR_CREATE",
        "FIN_AR_RECEIVE",
        "FIN_CONCIL",
        "CAD_VIEW",
        "CAD_EDIT",
        "RH_VIEW",
        "RH_APONTAR",
        "RH_VER_SALARIO",
        "RH_EDIT_SALARIO",
        "REPORT_VIEW",
        "BI_VIEW",
        "ADMIN_USERS",
        "ADMIN_PERFIS",
        "AJUDA_VIEW",
        "ASSISTENTES_IA_VIEW",
        "ATALHOS_VIEW",
        "NOTIFICACOES_VIEW",
        "SETTINGS_EMPRESA"
      ],
      "menus": [
        "dashboard",
        "calendario",
        "obras",
        "suprimentos",
        "estoques",
        "logistica",
        "equipamentos",
        "financeiro",
        "cadastros",
        "rh",
        "relatorios",
        "administracao",
        "ativos",
        "implementacoes",
        "ajuda",
        "assistentes-ia",
        "atalhos",
        "notificacoes",
        "ajustes"
      ]
    },
    "diretoria": {
      "nivel": 3,
      "label": "Diretoria",
      "descricao": "Visão executiva - BI, relatórios, aprovações altas",
      "permissoes": [
        "DASH_VIEW_EXEC",
        "CAL_VIEW",
        "OBRA_VIEW",
        "SUP_VIEW",
        "SUP_APPROVE",
        "EST_VIEW",
        "LOG_VIEW",
        "EQUIP_VIEW",
        "FIN_VIEW",
        "FIN_AP_CREATE",
        "FIN_AR_CREATE",
        "CAD_VIEW",
        "RH_VIEW",
        "REPORT_VIEW",
        "BI_VIEW",
        "AJUDA_VIEW",
        "ASSISTENTES_IA_VIEW",
        "NOTIFICACOES_VIEW"
      ],
      "menus": [
        "dashboard",
        "obras",
        "suprimentos",
        "estoques",
        "logistica",
        "financeiro",
        "cadastros",
        "rh",
        "relatorios",
        "ativos",
        "ajuda",
        "assistentes-ia",
        "notificacoes"
      ]
    },
    "financeiro": {
      "nivel": 4,
      "label": "Financeiro",
      "descricao": "Gestão financeira completa",
      "permissoes": [
        "DASH_VIEW_OPER",
        "OBRA_VIEW",
        "SUP_VIEW",
        "EST_VIEW",
        "LOG_VIEW",
        "FIN_VIEW",
        "FIN_LANC_CREATE",
        "FIN_LANC_EDIT",
        "FIN_AP_CREATE",
        "FIN_AP_PAY",
        "FIN_AP_EDIT",
        "FIN_AR_CREATE",
        "FIN_AR_RECEIVE",
        "FIN_AR_EDIT",
        "FIN_CONCIL",
        "CAD_VIEW",
        "REPORT_VIEW",
        "AJUDA_VIEW",
        "NOTIFICACOES_VIEW"
      ],
      "menus": [
        "dashboard",
        "obras",
        "suprimentos",
        "estoques",
        "logistica",
        "financeiro",
        "cadastros",
        "relatorios",
        "ajuda",
        "notificacoes"
      ]
    },
    "engenharia": {
      "nivel": 5,
      "label": "Engenharia",
      "descricao": "Gestão de obras, medições, orçamentos",
      "permissoes": [
        "DASH_VIEW_OPER",
        "CAL_VIEW",
        "CAL_CREATE_EVENT",
        "CAL_EDIT_EVENT",
        "OBRA_VIEW",
        "OBRA_CREATE",
        "OBRA_EDIT",
        "SUP_VIEW",
        "SUP_REQUEST",
        "EST_VIEW",
        "EST_TRANSFER",
        "LOG_VIEW",
        "LOG_CREATE_TRIP",
        "EQUIP_VIEW",
        "EQUIP_SCHEDULE",
        "CAD_VIEW",
        "CAD_EDIT",
        "RH_VIEW",
        "RH_APONTAR",
        "REPORT_VIEW",
        "ATIVOS_VIEW",
        "AJUDA_VIEW",
        "ASSISTENTES_IA_VIEW",
        "NOTIFICACOES_VIEW"
      ],
      "menus": [
        "dashboard",
        "calendario",
        "obras",
        "suprimentos",
        "estoques",
        "logistica",
        "equipamentos",
        "cadastros",
        "rh",
        "relatorios",
        "ativos",
        "ajuda",
        "assistentes-ia",
        "notificacoes"
      ]
    },
    "compras": {
      "nivel": 6,
      "label": "Compras",
      "descricao": "Gestão de compras, fornecedores, ordens",
      "permissoes": [
        "DASH_VIEW_OPER",
        "OBRA_VIEW",
        "SUP_VIEW",
        "SUP_REQUEST",
        "SUP_APPROVE",
        "SUP_OC_CREATE",
        "SUP_OC_APPROVE",
        "EST_VIEW",
        "EST_RECEIVE",
        "LOG_VIEW",
        "CAD_VIEW",
        "CAD_EDIT",
        "REPORT_VIEW",
        "AJUDA_VIEW",
        "NOTIFICACOES_VIEW"
      ],
      "menus": [
        "dashboard",
        "obras",
        "suprimentos",
        "estoques",
        "logistica",
        "cadastros",
        "relatorios",
        "ajuda",
        "notificacoes"
      ]
    },
    "almoxarifado": {
      "nivel": 7,
      "label": "Almoxarifado",
      "descricao": "Gestão de estoque e movimentações",
      "permissoes": [
        "DASH_VIEW_OPER",
        "OBRA_VIEW",
        "SUP_VIEW",
        "EST_VIEW",
        "EST_RECEIVE",
        "EST_TRANSFER",
        "EST_ADJUST",
        "LOG_VIEW",
        "CAD_VIEW",
        "REPORT_VIEW",
        "AJUDA_VIEW",
        "NOTIFICACOES_VIEW"
      ],
      "menus": [
        "dashboard",
        "obras",
        "suprimentos",
        "estoques",
        "logistica",
        "cadastros",
        "relatorios",
        "ajuda",
        "notificacoes"
      ]
    },
    "logistica": {
      "nivel": 8,
      "label": "Logística",
      "descricao": "Gestão de frota, viagens, motoristas",
      "permissoes": [
        "DASH_VIEW_OPER",
        "OBRA_VIEW",
        "EST_VIEW",
        "LOG_VIEW",
        "LOG_CREATE_TRIP",
        "LOG_APPROVE_TRIP",
        "EQUIP_VIEW",
        "EQUIP_SCHEDULE",
        "REPORT_VIEW",
        "AJUDA_VIEW",
        "ALERTAS_IA_VIEW",
        "NOTIFICACOES_VIEW"
      ],
      "menus": [
        "dashboard",
        "obras",
        "estoques",
        "logistica",
        "equipamentos",
        "relatorios",
        "ajuda",
        "assistentes-ia",
        "notificacoes"
      ]
    },
    "rh": {
      "nivel": 9,
      "label": "RH",
      "descricao": "Gestão de recursos humanos, folha, apontamentos",
      "permissoes": [
        "DASH_VIEW_OPER",
        "OBRA_VIEW",
        "RH_VIEW",
        "RH_APONTAR",
        "RH_VER_SALARIO",
        "RH_EDIT_SALARIO",
        "REPORT_VIEW",
        "AJUDA_VIEW",
        "NOTIFICACOES_VIEW"
      ],
      "menus": [
        "dashboard",
        "obras",
        "rh",
        "relatorios",
        "ajuda",
        "notificacoes"
      ]
    },
    "campo": {
      "nivel": 10,
      "label": "Campo",
      "descricao": "Trabalho de campo - SEM Financeiro, Cadastros, Admin, TI",
      "permissoes": [
        "DASH_VIEW_OPER",
        "CAL_VIEW",
        "CAL_CREATE_EVENT",
        "OBRA_VIEW",
        "EST_VIEW",
        "LOG_VIEW",
        "LOG_CREATE_TRIP",
        "EQUIP_VIEW",
        "RH_APONTAR",
        "AJUDA_VIEW",
        "NOTIFICACOES_VIEW"
      ],
      "menus": [
        "dashboard",
        "calendario",
        "obras",
        "estoques",
        "logistica",
        "equipamentos",
        "rh",
        "ajuda",
        "notificacoes"
      ]
    }
  },
  "modulos": {
    "DASH": "Dashboard",
    "CAL": "Calendário",
    "OBRA": "Obras",
    "SUP": "Suprimentos",
    "EST": "Estoques",
    "LOG": "Logística",
    "EQUIP": "Equipamentos",
    "FIN": "Financeiro",
    "CAD": "Cadastros",
    "RH": "RH",
    "REPORT": "Relatórios",
    "ADMIN": "Administração",
    "ATIVOS": "Ativos",
    "TI": "TI",
    "AJUDA": "Ajuda",
    "ASSISTENTES_IA": "Assistentes IA",
    "ATALHOS": "Atalhos",
    "NOTIFICACOES": "Notificações",
    "SETTINGS": "Ajustes"
  },
  "acoes": {
    "VIEW": "Visualizar",
    "CREATE": "Criar",
    "EDIT": "Editar",
    "DELETE": "Deletar",
    "APPROVE": "Aprovar",
    "PAY": "Pagar",
    "RECEIVE": "Receber",
    "TRANSFER": "Transferir",
    "ADJUST": "Ajustar",
    "MAINTAIN": "Manter",
    "SCHEDULE": "Agendar",
    "REQUEST": "Solicitar",
    "APONTAR": "Apontar",
    "VER_SALARIO": "Ver Salário",
    "EDIT_SALARIO": "Editar Salário"
  }
}